source "https://rubygems.org"

gem "rails", "~> 8.1.3"
gem "propshaft"
gem "sqlite3", "~> 2.0"
gem "puma", ">= 5.0"
gem "bcrypt", "~> 3.1"
gem "rack-cors"
gem "kaminari"
gem "tzinfo-data", platforms: %i[ windows jruby ]

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "bundler-audit", require: false
end

group :development do
  gem "rubocop-rails", require: false
end
