puts "Seeding database..."

# ---- Test user (idempotent) ----
# Used for local development/testing
test_email = "test@example.com"

User.find_or_create_by!(email: test_email) do |u|
  u.first_name = "Test"
  u.last_name = "User"
  u.phone = "+1-555-0000"
  u.password = "Password123!"
  u.password_confirmation = "Password123!"
end

Property.create!([
  {
    title: "New Apartment Nice View",
    description: "Beautiful Huge 1 Family House In Heart Of Westbury. Newly Renovated With New Wood",
    price: 34900,
    address: "Belmont Gardens",
    city: "Chicago",
    state: "IL",
    zip_code: "60618",
    bedrooms: 3,
    bathrooms: 2,
    square_feet: 3450,
    property_type: "Apartment",
    status: "for_rent",
    featured: true,
    image_url: "assets/images/property-1.svg",
    agent_name: "William Seklo",
    agent_phone: "+1-555-0101",
    agent_email: "william@prismaproperty.com"
  },
  {
    title: "Modern Apartments",
    description: "Beautiful Huge 1 Family House In Heart Of Westbury. Newly Renovated With New Wood",
    price: 45000,
    address: "Belmont Gardens",
    city: "Chicago",
    state: "IL",
    zip_code: "60618",
    bedrooms: 3,
    bathrooms: 2,
    square_feet: 3450,
    property_type: "Apartment",
    status: "for_sale",
    featured: true,
    image_url: "assets/images/property-2.svg",
    agent_name: "William Seklo",
    agent_phone: "+1-555-0101",
    agent_email: "william@prismaproperty.com"
  },
  {
    title: "Comfortable Apartment",
    description: "Beautiful Huge 1 Family House In Heart Of Westbury. Newly Renovated With New Wood",
    price: 28000,
    address: "Belmont Gardens",
    city: "Chicago",
    state: "IL",
    zip_code: "60618",
    bedrooms: 3,
    bathrooms: 2,
    square_feet: 3450,
    property_type: "Apartment",
    status: "for_rent",
    featured: true,
    image_url: "assets/images/property-3.svg",
    agent_name: "William Seklo",
    agent_phone: "+1-555-0101",
    agent_email: "william@prismaproperty.com"
  },
  {
    title: "Luxury Villa in Rego Park",
    description: "Beautiful Huge 1 Family House In Heart Of Westbury. Newly Renovated With New Wood",
    price: 65000,
    address: "Belmont Gardens",
    city: "Chicago",
    state: "IL",
    zip_code: "60618",
    bedrooms: 3,
    bathrooms: 2,
    square_feet: 3450,
    property_type: "Villa",
    status: "for_rent",
    featured: true,
    image_url: "assets/images/property-4.svg",
    agent_name: "William Seklo",
    agent_phone: "+1-555-0101",
    agent_email: "william@prismaproperty.com"
  },
  {
    title: "Studio Apartment in Manhattan",
    description: "Sleek and modern studio apartment in the heart of Manhattan. Floor-to-ceiling windows with stunning city views. Features hardwood floors, stainless steel appliances, and a spa-like bathroom. Steps away from Central Park and world-class dining.",
    price: 2850,
    address: "350 West 42nd Street, Apt 18C",
    city: "New York",
    state: "NY",
    zip_code: "10036",
    bedrooms: 0,
    bathrooms: 1,
    square_feet: 480,
    property_type: "Studio",
    status: "for_rent",
    featured: true,
    image_url: "assets/images/property-1.svg",
    agent_name: "Sarah Mitchell",
    agent_phone: "+1-555-0202",
    agent_email: "sarah@prismaproperty.com"
  },
  {
    title: "Beachfront Condo in Miami",
    description: "Stunning beachfront condominium with panoramic ocean views. Resort-style amenities including infinity pool, fitness center, and private beach access. Luxury finishes throughout with impact-resistant windows and a gourmet kitchen.",
    price: 725000,
    address: "1200 Collins Avenue, Unit 2204",
    city: "Miami",
    state: "FL",
    zip_code: "33139",
    bedrooms: 2,
    bathrooms: 2,
    square_feet: 1350,
    property_type: "Condo",
    status: "for_sale",
    featured: true,
    image_url: "assets/images/property-2.svg",
    agent_name: "Carlos Ramirez",
    agent_phone: "+1-555-0303",
    agent_email: "carlos@prismaproperty.com"
  },
  {
    title: "Suburban Family Home in Dallas",
    description: "Spacious family home in a top-rated school district. Open floor plan with gourmet kitchen, large family room, and covered patio. Features a game room, home office, and a beautifully landscaped backyard with a saltwater pool.",
    price: 485000,
    address: "742 Maple Creek Drive",
    city: "Dallas",
    state: "TX",
    zip_code: "75234",
    bedrooms: 4,
    bathrooms: 3,
    square_feet: 2800,
    property_type: "House",
    status: "for_sale",
    featured: false,
    image_url: "assets/images/property-3.svg",
    agent_name: "William Seklo",
    agent_phone: "+1-555-0101",
    agent_email: "william@prismaproperty.com"
  },
  {
    title: "Downtown Loft in San Francisco",
    description: "Industrial-chic loft in the vibrant SoMa district. Exposed brick walls, soaring ceilings, and polished concrete floors. Open concept living with a chef's kitchen and private rooftop access with city skyline views.",
    price: 3900,
    address: "88 Townsend Street, Loft 412",
    city: "San Francisco",
    state: "CA",
    zip_code: "94107",
    bedrooms: 1,
    bathrooms: 1,
    square_feet: 1100,
    property_type: "Loft",
    status: "for_rent",
    featured: true,
    image_url: "assets/images/property-4.svg",
    agent_name: "Sarah Mitchell",
    agent_phone: "+1-555-0202",
    agent_email: "sarah@prismaproperty.com"
  },
  {
    title: "Mountain Cabin Retreat in Denver",
    description: "Rustic luxury mountain cabin nestled in the Rocky Mountain foothills. Features a stone fireplace, vaulted ceilings with exposed beams, and a wrap-around deck with breathtaking mountain views. Perfect as a vacation home or year-round retreat.",
    price: 520000,
    address: "1567 Aspen Ridge Road",
    city: "Denver",
    state: "CO",
    zip_code: "80202",
    bedrooms: 3,
    bathrooms: 2,
    square_feet: 1950,
    property_type: "Cabin",
    status: "for_sale",
    featured: false,
    image_url: "assets/images/property-1.svg",
    agent_name: "Carlos Ramirez",
    agent_phone: "+1-555-0303",
    agent_email: "carlos@prismaproperty.com"
  },
  {
    title: "Colonial House in Boston",
    description: "Classic colonial home in the historic Beacon Hill neighborhood. Beautifully restored with original hardwood floors, crown molding, and a wood-burning fireplace. Features a gourmet kitchen, private garden, and detached garage.",
    price: 1250000,
    address: "42 Chestnut Street",
    city: "Boston",
    state: "MA",
    zip_code: "02108",
    bedrooms: 5,
    bathrooms: 4,
    square_feet: 3600,
    property_type: "Colonial",
    status: "for_sale",
    featured: true,
    image_url: "assets/images/property-3.svg",
    agent_name: "William Seklo",
    agent_phone: "+1-555-0101",
    agent_email: "william@prismaproperty.com"
  }
])

puts "Seeding complete!"
